### ISSUE TITLE
Question about cluster friendly functionality

### ISSUE THREAD

**Issue by niksy** [WebReflection/id-promise#1]
In the readme you mention that module is "cluster friendly".

I wanted to know does that mean if I run my application in e.g. [PM2 cluster mode](https://pm2.keymetrics.io/docs/usage/cluster-mode/) and create Promise with `id-promise`, that same Promise will be shared and waited for resolution across created (cluster) instances of application?

**Comment by WebReflection** [comment]
unfortunately PM2 doesn't allow any code to run in master so ... the short answer is no, it's cluster friendly but not PM2 clusters friendly 😢
